// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Drivetrain;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Turn extends CommandBase {
    private static final Logger LOG = LoggerFactory.getLogger(Turn.class);
    private double startHeading;
    private double targetHeading;
    private double currentHeading;
    private int multiplyHeading;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final Drivetrain m_drivetrain;
    private double m_degrees;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public Turn(double degrees, Drivetrain subsystem) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_degrees = degrees;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_drivetrain = subsystem;
        addRequirements(m_drivetrain);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        SmartDashboard.putNumber("TurnDegrees", 0);
    }

    public void turnLeft (double speed) {
        m_drivetrain.tankDrive(-speed, -speed);
    }

    public void turnRight (double speed) {
        LOG.info("In turnRight");
        m_drivetrain.tankDrive(speed, speed);
    }
    
    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_degrees = SmartDashboard.getNumber("TurnDegrees", 0);
        startHeading = m_drivetrain.getHeading();
        LOG.info("StartHeading = {}", startHeading);
        targetHeading = startHeading+m_degrees;
        LOG.info("TargetHeading = {}", targetHeading);
        if (targetHeading >= 360) {
            multiplyHeading = (int) Math.floor(targetHeading / 360);
        } else {
            multiplyHeading = 1;
        }
        LOG.info("MultiplyHeading = {}", multiplyHeading);
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        LOG.info("Turn.execute() running");
        SmartDashboard.putNumber("CurrentHeading", m_drivetrain.getHeading());
        SmartDashboard.putNumber("TargetHeading", targetHeading);
        SmartDashboard.putNumber("StartHeading", startHeading);
        if (m_degrees > 0) {
            LOG.info("Turning Right");
            turnRight(0.75);
        } else if (m_degrees < 0) {
            LOG.info("Turning Left");
            turnLeft(0.75);
        } else {
            LOG.info("0 Degrees Passed");
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        LOG.info("Turn Stopped, interrupted: {}", interrupted);
        m_drivetrain.stopDriving();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        currentHeading = m_drivetrain.getHeading();
        double multipliedHeading = currentHeading * multiplyHeading;
        LOG.debug("In IsFinished");
        LOG.debug("m_degrees = {}, StartHeading = {}, TargetHeading = {}, CurrentHeading = {}", m_degrees, startHeading, targetHeading, m_drivetrain.getHeading());
        if (m_degrees > 0) {
            LOG.debug("In Turn/Isfinished/first if statement");
            if (multipliedHeading > targetHeading) {
                LOG.debug("Done Turning Right");
                return true;
            } else {
                return false;
            }
        } else if (m_degrees < 0) {
            if (multipliedHeading < targetHeading) {
                LOG.debug("Done Turning Left");
                return true;
            } else {
                return false;
            }
        } else {
            LOG.debug("0 Degrees Passed");
            return true;
        }
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
