// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.PS4Controller.Button;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;

import javax.xml.namespace.QName;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import frc.robot.Constants;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Intake extends SubsystemBase {

    private static final Logger LOG = LoggerFactory.getLogger(Intake.class);
    
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    final WPI_TalonFX intakeMotor1; 
    final WPI_TalonFX intakeMotor2; 
    final WPI_TalonFX intakeMotor3;  
    private static int intakeId1 = Constants.Transport.transportMotor1;
    private static int intakeId2 = Constants.Transport.transportMotor2; 
    private static int intakeId3 = Constants.Transport.transportMotor3; 
    private static XboxController intakeButton = new XboxController(Constants.XboxButtons.xButtonId);
    
  



    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    
    public Intake() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    
    intakeMotor1 = new WPI_TalonFX(intakeId1); 
    intakeMotor2 = new WPI_TalonFX(intakeId2);
    intakeMotor3 = new WPI_TalonFX(intakeId3); 

    if (intakeButton.isConnected())  {

     if (intakeButton.getXButtonPressed() == true) {
        // Configurable speeds 
        intakeMotor1.set(ControlMode.Velocity, 1000);
        intakeMotor2.set(ControlMode.Velocity, 1000);
        intakeMotor3.set(ControlMode.Velocity, 1000);

    }  else {
        intakeMotor1.close();
        intakeMotor2.close();
        intakeMotor3.close();                       
    }

    



    } 
    

    
    




    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    
    


    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run


    
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

 